// tools/lib/project.js — the ONE Albers projection + viewBox fit, shared by
// every build script.
//
// Why this file exists: data/map.js (borders) and data/stations.js (cities)
// are generated by two different scripts, but they must land in the same pixel
// space or every station is offset from the country it belongs to. So the
// projection lives here, and the fit — the scale/offset derived from the map's
// bounding box — is COMPUTED ONCE by tools/build-map.js, written to
// tools/lib/fit.json, and READ BACK by tools/build-stations.js. It is never
// recomputed from a different point set.

'use strict';
const fs = require('fs');
const path = require('path');

const VIEW = { w: 1000, h: 700, margin: 20 };

// Albers equal-area conic, phi1=43 phi2=62 lambda0=15 phi0=52.
const D = Math.PI / 180;
const P1 = 43 * D, P2 = 62 * D, L0 = 15 * D, P0 = 52 * D;
const N = (Math.sin(P1) + Math.sin(P2)) / 2;
const C = Math.cos(P1) ** 2 + 2 * N * Math.sin(P1);
const RHO0 = Math.sqrt(C - 2 * N * Math.sin(P0)) / N;

function albers(lon, lat) {
  const rho = Math.sqrt(C - 2 * N * Math.sin(lat * D)) / N;
  const th = N * (lon * D - L0);
  // y is negated: the projection is north-up but the viewBox is y-down.
  return [rho * Math.sin(th), -(RHO0 - rho * Math.cos(th))];
}

// Emitted precision. Applied before any downstream geometry pass so every
// consumer sees the same numbers.
const rnd = x => Math.round(x * 10) / 10;

// Uniform scale + centring for a set of projected [x,y] points.
function computeFit(points) {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const p of points) {
    if (p[0] < minX) minX = p[0]; if (p[0] > maxX) maxX = p[0];
    if (p[1] < minY) minY = p[1]; if (p[1] > maxY) maxY = p[1];
  }
  const k = Math.min((VIEW.w - 2 * VIEW.margin) / (maxX - minX),
                     (VIEW.h - 2 * VIEW.margin) / (maxY - minY));
  return {
    k,
    offX: (VIEW.w - (maxX - minX) * k) / 2 - minX * k,
    offY: (VIEW.h - (maxY - minY) * k) / 2 - minY * k,
  };
}

const FIT_FILE = path.join(__dirname, 'fit.json');

function saveFit(fit) {
  fs.writeFileSync(FIT_FILE, JSON.stringify(fit, null, 2) + '\n');
}

function loadFit() {
  if (!fs.existsSync(FIT_FILE)) {
    throw new Error('tools/lib/fit.json missing — run `node tools/build-map.js` first.');
  }
  return JSON.parse(fs.readFileSync(FIT_FILE, 'utf8'));
}

// lon/lat -> viewBox pixels, using the map's stored fit.
function toView(lon, lat, fit) {
  const p = albers(lon, lat);
  return [rnd(p[0] * fit.k + fit.offX), rnd(p[1] * fit.k + fit.offY)];
}

module.exports = { VIEW, albers, computeFit, saveFit, loadFit, toView, rnd };
