// test/node.js — headless runner. `node test/node.js` from the project root.
// Works because the project uses globals, not modules: every file is evaluated
// into this one shared context, exactly as <script src> would. Missing files
// are skipped, so the harness runs while the map is still being authored.
// Keep this list in sync with the <script> tags in tests.html.
const fs = require('fs'), vm = require('vm'), path = require('path');
const root = path.join(__dirname, '..');
const SCRIPTS = [
  'core/rng.js', 'core/exact.js', 'core/util.js', 'core/state.js', 'core/vision.js',
  'data/tuning.js',
  'data/map.js',   // generated by tools/build-map.js from Natural Earth TopoJSON
  'data/stations.js', 'data/scenario.js',
  'sim/commands.js', 'sim/growth.js', 'sim/movement.js', 'sim/combat.js',
  'sim/relations.js', 'sim/victory.js', 'sim/step.js',
  'ai/score.js', 'ai/ai.js',
  // The ONLY render/ file this harness loads. render/help.js declares the
  // guide's derived content (numbers off BAL and STATIONS) at the top level and
  // touches no DOM until helpShow() is called, so it evaluates cleanly in a
  // context with no `document` and no `window` — its exports are guarded for
  // exactly that. test/help-tests.js asserts the content against the same data.
  'render/help.js',
  // The second render/ file here, for the same reason: render/standings.js
  // computes its ranking from state alone, touches no DOM until the rail calls
  // build(), and guards its railAddSection() registration — so it evaluates in
  // a context with no `document` and no `window`.
  'render/standings.js',
  'test/asserts.js', 'test/exact-tests.js', 'test/queue-tests.js', 'test/ai-tests.js',
  'test/fog-tests.js',
  'test/help-tests.js',
  'test/scenarios-standings.js', 'test/scenarios-routes.js',
  'test/scenarios-routeflow.js',
  'test/runner.js',
];
for (const rel of SCRIPTS) {
  const f = path.join(root, rel);
  if (!fs.existsSync(f)) continue;
  try { vm.runInThisContext(fs.readFileSync(f, 'utf8'), { filename: rel }); }
  catch (e) { console.error('LOAD ERROR in ' + rel + ': ' + e.message); process.exit(2); }
}
runAllTests();
process.stdout.write(formatResults() + '\n');
process.exit(summarizeTests().fail === 0 ? 0 : 1);
