"use strict";
// core/vision.js — the fog gate. Milestone 5.7, stages 1 and 2.
//
// Four functions decide what a power may READ from a complete state:
//
//   stationVision(sid)              -> 1 | 2            static, from the record
//   visibleTo(state, pid)           -> { sid: 0|2 }     live sight, pure
//   observeTick(state)              -> writes state.seen (the only mutation)
//   believedStation(state, pid,sid) -> { owner, units, connected, tick, level }
//
// The state stays TOTAL and the reads are made PARTIAL
// (02-visibility-and-sea.md §1). That is the whole architecture: two states
// that differ only in what somebody has seen would no longer be comparable, so
// seeded replay, byte-identical 1x-vs-4x and headless determinism all depend on
// fog living outside the simulation.
//
// ---------------------------------------------------------------------------
// "Visibility is derived, never stored" — and yet state.seen exists.
// Resolving the apparent contradiction, because it will be read as one.
// ---------------------------------------------------------------------------
//
// 02-visibility-and-sea.md §1 says, in bold: *"Visibility is derived, never
// stored, and the sim state stays complete."* Stage 2 adds `state.seen`, which
// looks exactly like the thing that sentence forbids. It is not, and the
// reason is that the doc names one object where there are two:
//
//   VISIBILITY   { sid: 0 | 2 } — a pure function of (who owns what, LINKS,
//                station vision). Every input is a fact about the board RIGHT
//                NOW, so it is fully reconstructable from the present and
//                storing it would be a second copy of a fact that every single
//                capture invalidates (known-issues #9). visibleTo() below is
//                that function, it holds a cache of nothing, and the rule
//                applies to it exactly and without amendment.
//
//   MEMORY       "what pid saw at sid, and when". A log of PAST observation.
//                No snapshot of the present contains it: "France saw Brussels
//                at t=3120, holding 14.2 units" is not derivable from the board
//                at t=3500 by any function whatsoever. It is new information,
//                generated by the passage of time, and the only thing that can
//                be done with information that cannot be recomputed is to
//                store it. The doc never says where, because the doc never
//                separates the two objects.
//
// The three-level table in §1 is then a COMPOSITION of the two, not a fourth
// thing: level = visible(now) ? 2 : remembered(ever) ? 1 : 0. That composition
// is believedStation(), and it is the only function here that can mint a 1.
// visibleTo() still never returns one, which is why its contract is unchanged
// from stage 1 and its tests did not move.
//
// ---------------------------------------------------------------------------
// Why memory lives in GAME STATE (state.seen) and not in the renderer
// ---------------------------------------------------------------------------
//
// Three forcing reasons, any one of them sufficient:
//
//   1. SYMMETRY. §1: "The AI gets the same fog. Symmetric, without exception."
//      Memory held by the renderer gives the player ternary fog and the AI
//      BINARY fog — the AI would see a station or not see it, and could never
//      be baited by a number that was true a minute ago. That is asymmetric in
//      the AI's favour on precisely the axis the design says fog exists to
//      create: "decide whether last minute's number is still true".
//
//   2. HEADLESS COVERAGE. test/node.js and tools/balance.js load NO file under
//      render/ (that is 5.6c's stated lesson and known-issues #9, #15, #20).
//      Memory outside state means milestone 6 tunes every constant in BAL.AI
//      against a memoryless AI, and then ships a different game.
//
//   3. SNAPSHOTS. snapshot() is JSON.parse(JSON.stringify(state)) and nothing
//      else. Anything outside `state` does not survive it, so a restored game
//      would diverge from the run it was saved out of. This is the same
//      argument that already put state.rng, state.aiMemo and state.aiLog
//      inside state rather than beside it.
//
// ---------------------------------------------------------------------------
// Why this file is in core/ and not anywhere else
// ---------------------------------------------------------------------------
//
//   sim/     Forbidden by the design. The moment fog is inside the sim,
//            determinism testing gets much harder and every existing sim test
//            needs a visibility fixture. `test/fog-tests.js` asserts as a
//            TESTED FACT that no file under sim/ so much as names these
//            functions, because a comment saying "sim must not call this" is
//            not a check.
//   render/  test/node.js loads no render/ file at all, so fog would ship with
//            ZERO headless coverage (known-issues #9, #15, #20 are all this
//            same hole). And ai/score.js loads before every render file, so the
//            AI could not call it.
//   ai/      Declared optional — a build with ai/ deleted must still run — so
//            the renderer's masking would vanish along with the AI.
//   data/    May not reference state (01-data-schema.md).
//
// core/ is what is left, and it is also correct: this is a derived fact about
// state, which is what core/state.js is for.
//
// ---------------------------------------------------------------------------
// Performance — settled. DO NOT ADD A CACHE.
// ---------------------------------------------------------------------------
//
// Measured on the live 108-station / 236-link board, this implementation, seed
// 100 at t=4000, 20,000 calls each:
//
//   visibleTo, mid-game (11 of 108 owned)        24.3us
//   visibleTo, worst case (100 of 108 owned)     38.6us
//   stepTick, same board                        671.5us
//
// So the worst case is 5.8% of one tick and 0.23% of a 16.67ms frame, called
// once per frame per viewer. The cost is dominated by allocating the 108-key
// result — which is the price of being pure, and is not worth removing. A
// per-frame recompute with no stored index is correct, and it honours
// known-issues #9's warning against an index that is a second copy of a fact
// invalidated by every single capture.
//
// If profiling ever genuinely contradicts that, the sanctioned memo key is
// (state object identity, state.ownerEpoch, pid) — the same key
// `_moveOwnSearch`'s `_ownRouteCache` already uses in sim/movement.js, because
// ownerEpoch is the exact and total invalidation signal for visibility. Report
// the measurement first; do not build it unilaterally.
//
// ---------------------------------------------------------------------------
// House rules honoured here
// ---------------------------------------------------------------------------
//
//   * Private helpers are prefixed `_vis`, by FILE and not by subsystem
//     (known-issues #12 — `_ai` was not specific enough and #9 recurred).
//   * Iteration is over the sorted STATION_IDS and over LINKS in array order,
//     never over Object.keys(state.stations): key order is a real determinism
//     hazard and no other test can see it.
//   * Nothing in this file touches the DOM, the wall clock, or unseeded
//     entropy. (core/util.js does reach the DOM, so core/ is not DOM-free as a
//     layer — this file is, and is asserted to be.)
//   * visibleTo is PURE: it reads state and returns a fresh object. It writes
//     nothing, not even a scratch field on a station. So is believedStation.
//     observeTick is the ONE mutating function in this file, and it writes
//     exactly one field (state.seen) — see its own comment for why it is not a
//     phase of stepTick.

// How many link-hops a station sees for whoever holds it.
//
// The value lives on the station record in data/stations.js and is assigned by
// tools/build-stations.js: 1 by default, 2 for every `defensive` station and
// for a short authored table of observation points (the Straits of Dover, the
// Bosphorus, the Skagerrak, the German Baltic shore, the Strait of Otranto).
// It is a NUMERIC PROPERTY rather than a fifth station type because 00-vision.md
// §8 already spends the silhouette budget on the four types that exist.
//
// Defaults to 1 for an unknown id or a station record written before the field
// existed, so a stale snapshot degrades to minimum vision rather than throwing.
function stationVision(sid) {
  if (typeof STATIONS !== "object" || !STATIONS) return 1;
  var st = STATIONS[sid];
  if (!st) return 1;
  var v = st.vision;
  return (typeof v === "number" && isFinite(v) && v >= 1) ? v : 1;
}

// What `pid` may read on this board, as { stationId: level }.
//
//   2  visible — held by pid, or within stationVision() hops of a station it
//                holds, counted over LINKS
//   0  hidden  — everything else
//
// THIS FUNCTION NEVER RETURNS 1, and that is permanent rather than unfinished.
// Level 1 is "seen before, not seen now", which is a claim about the past;
// this function is a claim about the present and takes no memory as input.
// believedStation() composes the two and is the only place a 1 is minted.
//
// Vision traverses ALL links regardless of who holds the ground in between,
// including `sea: true` crossings. Sight is not a march: an army may not walk
// through a rival's city, but a lookout on the far shore still sees it.
//
// Every station id gets an entry, so a caller never has to distinguish "hidden"
// from "absent" — a missing key is the shape that produces an accidental
// `undefined` in a renderer.
function visibleTo(state, pid) {
  var out = {};
  if (typeof STATION_IDS === "undefined" || !STATION_IDS.length) return out;

  var ids = STATION_IDS;
  var i, sid;

  // `budget` is hops of sight REMAINING at a station: -1 means unreached, 0
  // means seen but with nothing left to pass on. Seeding it with the owner's
  // own vision and decrementing per hop is what lets a 2-hop citadel and a
  // 1-hop city share one traversal.
  var budget = {};
  for (i = 0; i < ids.length; i++) {
    sid = ids[i];
    out[sid] = 0;
    budget[sid] = -1;
  }

  var stations = (state && state.stations) ? state.stations : null;
  if (!stations) return out;

  var reach = 0;
  for (i = 0; i < ids.length; i++) {
    sid = ids[i];
    var st = stations[sid];
    if (!st || st.owner !== pid) continue;
    out[sid] = 2;
    var v = stationVision(sid);
    if (v > budget[sid]) budget[sid] = v;
    if (v > reach) reach = v;
  }
  if (!reach) return out;                 // holds nothing: sees nothing

  if (typeof LINKS === "undefined" || !LINKS) return out;
  _visRelax(out, budget, reach);
  return out;
}

// Spread `budget` outward over LINKS until it is exhausted.
//
// One pass per hop of the deepest sight on the board (`reach`, at most 2 today)
// is sufficient: each pass can only ever move sight forward, so `reach` passes
// reach everything reachable. A pass may in fact carry sight further than one
// hop when link order happens to favour it, which is harmless — a budget is
// only ever written as `neighbour's budget - 1`, so every value it holds is one
// a real path could have delivered.
//
// Deterministic without depending on link order: the result is the fixpoint of
// a max, so no ordering can change it. LINKS is walked in array order anyway.
function _visRelax(out, budget, reach) {
  for (var hop = 0; hop < reach; hop++) {
    var changed = false;
    for (var j = 0; j < LINKS.length; j++) {
      var l = LINKS[j];
      // Sea crossings are traversed exactly like roads. `l.sea` is deliberately
      // not read here; a lookout does not care what is between.
      if (budget[l.a] - 1 > budget[l.b]) {
        budget[l.b] = budget[l.a] - 1;
        out[l.b] = 2;
        changed = true;
      }
      if (budget[l.b] - 1 > budget[l.a]) {
        budget[l.a] = budget[l.b] - 1;
        out[l.a] = 2;
        changed = true;
      }
    }
    if (!changed) return;
  }
}

// ---------------------------------------------------------------------------
// Memory — observeTick(state)
//
// Writes, for every alive power, what that power can currently see. This is
// the ONLY function in this file that mutates, and it mutates exactly one
// field: state.seen.
//
// ---------------------------------------------------------------------------
// WHY IT IS NOT A PHASE OF stepTick
// ---------------------------------------------------------------------------
//
// It is called from the top of aiTick() (ai/ai.js), not from SIM_PHASES.
//
// known-issues #13 is the whole argument. When aiTick became phase 0 of
// stepTick, "every sim test became a test of the sim plus seven AIs playing
// inside it". ONE test failed. The other 78 kept passing while measuring
// something different from what they claimed, and nothing would have said so.
// Fog must not repeat that: a seventh entry in SIM_PHASES would silently
// change the meaning of every existing test of the tick a second time.
//
// aiTick is the right host and needs no new machinery to be one. It already
// runs outside the six pinned phases, already runs every tick, is already
// optional (a build with no ai/ still runs — it simply does not remember, and
// nothing but the renderer would notice), and is already the file that
// state.aiEnabled=false silences for test isolation. Riding it means fog
// inherits every isolation property the AI already paid for.
//
// It is called BEFORE the per-power decision loop and, deliberately, before
// that loop's `state.human` skip: a power observes whether or not it is
// AI-driven. The human's memory is what the renderer draws.
//
// ---------------------------------------------------------------------------
// DETERMINISM
// ---------------------------------------------------------------------------
//
// Pure function of state, writing into state, at a fixed point of a fixed
// phase. It draws nothing from state.rng, reads no wall clock, and iterates
// POWER_IDS and STATION_IDS — the sorted arrays — never Object.keys(). The
// throttle is `state.tick % OBSERVE_INTERVAL`, off the sim clock, so 4x
// (which is only ever MORE TICKS, never bigger ones) observes on exactly the
// same ticks 1x does.
//
// `neutral` is skipped. It is a real power id holding 101 of 108 stations at
// turn zero, but it takes no decisions, has no capital and is never rendered
// from, so a memory for it would be the largest single object in the state and
// would never be read by anything.
function observeTick(state) {
  if (!state || !state.stations) return;
  if (typeof STATION_IDS === "undefined" || typeof POWER_IDS === "undefined") return;

  // Defaults to 1 (observe every tick) if data/tuning.js has not loaded, which
  // is slow but never wrong. A zero or a non-integer would make the modulo
  // meaningless, so anything unusable falls back the same way.
  var iv = 1;
  if (typeof BAL !== "undefined" && BAL && BAL.FOG) {
    var raw = BAL.FOG.OBSERVE_INTERVAL;
    if (typeof raw === "number" && isFinite(raw) && raw >= 1) iv = Math.floor(raw);
  }
  if (iv > 1 && (state.tick % iv) !== 0) return;

  // A state built before this field existed — a restored snapshot from an
  // older build, a hand-made test fixture — reads as "nobody has seen
  // anything" rather than throwing.
  if (!state.seen) state.seen = {};

  for (var p = 0; p < POWER_IDS.length; p++) {
    var pid = POWER_IDS[p];
    if (pid === "neutral") continue;
    var power = state.powers ? state.powers[pid] : null;
    if (!power || power.alive === false) continue;

    var vis = visibleTo(state, pid);
    var mem = state.seen[pid] || (state.seen[pid] = {});

    for (var i = 0; i < STATION_IDS.length; i++) {
      var sid = STATION_IDS[i];
      // LEVEL 0 AND LEVEL 1 ARE BOTH SKIPPED, and for different reasons.
      // Level 0 has never been seen and writing it would destroy the
      // distinction the whole feature rests on. Level 1 cannot occur here:
      // visibleTo never returns one.
      if (vis[sid] !== 2) continue;
      var st = state.stations[sid];
      if (!st) continue;
      _visRemember(mem, sid, st, state.tick);
    }
  }
}

// One observation, written in place.
//
// Short keys (o/u/c/t) because this object is 7 powers x up to 108 stations
// and it goes through JSON.stringify on every snapshot; long keys would more
// than double the serialised size of the whole state for no reader's benefit.
//
// The record is REUSED rather than replaced, and `u` is copied field by field
// rather than by reference: a stored reference to the live station.units would
// make every remembered garrison update itself, which is the exact opposite of
// the feature and would look correct in every test that only checks the owner.
function _visRemember(mem, sid, st, tick) {
  var rec = mem[sid];
  if (!rec) {
    rec = mem[sid] = { o: null, u: { infantry: 0, artillery: 0, armour: 0 }, c: true, t: 0 };
  }
  rec.o = st.owner;
  rec.u.infantry = st.units.infantry;
  rec.u.artillery = st.units.artillery;
  rec.u.armour = st.units.armour;
  rec.c = st.connected !== false;
  rec.t = tick;
  return rec;
}

// What `pid` believes is at `sid`, which is the three-level table of
// 02-visibility-and-sea.md §1 evaluated for one station:
//
//   { owner, units, connected, tick, level }
//
//   level 2  live — owner/units/connected are the true board, tick is now
//   level 1  fogged — owner/units/connected are AS OF `tick`, which is when
//            this power last saw the station. `units` is stale and the caller
//            must say so on screen; `tick` is what lets it.
//   level 0  hidden — owner/units/connected are all null and tick is -1.
//            Null rather than zero on purpose: a zero garrison is a real and
//            meaningful board state, and a renderer that printed one for
//            ground nobody has ever visited would be inventing intelligence.
//
// `units` is always a FRESH object (or null). Handing back the stored record's
// own bundle would let one careless caller edit another power's memory.
//
// COST. Deriving `level` needs live visibility, and visibleTo is 24-38us — so
// this is safe for one station per frame (the hovered city) and is O(n^2) in a
// loop over the board, which is the same honest warning stationSuppliedBy
// carries in core/state.js. A caller that wants the whole board passes its own
// visibleTo result as the optional 4th argument and pays for it once.
function believedStation(state, pid, sid, vis) {
  var out = { owner: null, units: null, connected: null, tick: -1, level: 0 };
  if (!state || !state.stations || !state.stations[sid]) return out;

  var level = 0;
  if (vis && typeof vis[sid] === "number") level = vis[sid];
  else level = visibleTo(state, pid)[sid] || 0;

  if (level === 2) {
    var st = state.stations[sid];
    out.owner = st.owner;
    out.units = { infantry: st.units.infantry, artillery: st.units.artillery, armour: st.units.armour };
    out.connected = st.connected !== false;
    out.tick = state.tick;
    out.level = 2;
    return out;
  }

  var mem = (state.seen && state.seen[pid]) ? state.seen[pid][sid] : null;
  if (!mem) return out;                                  // never seen: level 0

  out.owner = mem.o;
  out.units = { infantry: mem.u.infantry, artillery: mem.u.artillery, armour: mem.u.armour };
  out.connected = mem.c;
  out.tick = mem.t;
  out.level = 1;
  return out;
}
